### ISSUE TITLE
使用或覆盖了已过时的 API

### ISSUE THREAD

**Issue by MonkeyInWind0** [wu9007/qrcode_scanner#101]
注: /.../.pub-cache/hosted/pub.flutter-io.cn/qrscan-0.2.22/android/src/main/java/com/shinow/qrscan/QrscanPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

I/Timeline(11263): Timeline: Activity_launch_request time:603319284 intent:Intent { cmp=com.example.PCControlClient/com.shinow.qrscan.SecondActivity }
D/ViewContentFactory(11263): initViewContentFetcherClass
I/ContentCatcher(11263): ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory(11263): createInterceptor took 0ms
I/ContentCatcher(11263): Interceptor : Catcher list invalid for com.example.PCControlClient@com.shinow.qrscan.SecondActivity@195247136
I/ContentCatcher(11263): Interceptor : Get featureInfo from config pick_mode
W/TypefaceUtils(11263): getFontNames failed
W/TypefaceUtils(11263): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference
W/TypefaceUtils(11263): 	at miui.util.TypefaceUtils.getFontNames(TypefaceUtils.java:578)
W/TypefaceUtils(11263): 	at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:532)
W/TypefaceUtils(11263): 	at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:524)
W/TypefaceUtils(11263): 	at android.widget.TextView.setTypeface(TextView.java:3709)
W/TypefaceUtils(11263): 	at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2106)
W/TypefaceUtils(11263): 	at android.widget.TextView.<init>(TextView.java:1612)
W/TypefaceUtils(11263): 	at android.widget.TextView.<init>(TextView.java:818)
W/TypefaceUtils(11263): 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:99)
W/TypefaceUtils(11263): 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
W/TypefaceUtils(11263): 	at com.shinow.qrscan.SecondActivity.onCreate(SecondActivity.java:40)
W/TypefaceUtils(11263): 	at android.app.Activity.performCreate(Activity.java:7040)
W/TypefaceUtils(11263): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
W/TypefaceUtils(11263): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
W/TypefaceUtils(11263): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
W/TypefaceUtils(11263): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
W/TypefaceUtils(11263): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
W/TypefaceUtils(11263): 	at android.os.Handler.dispatchMessage(Handler.java:105)
W/TypefaceUtils(11263): 	at android.os.Looper.loop(Looper.java:173)
W/TypefaceUtils(11263): 	at android.app.ActivityThread.main(ActivityThread.java:6698)
W/TypefaceUtils(11263): 	at java.lang.reflect.Method.invoke(Native Method)
W/TypefaceUtils(11263): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/TypefaceUtils(11263): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
W/TypefaceUtils(11263): getFontNames failed
W/TypefaceUtils(11263): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference
W/TypefaceUtils(11263): 	at miui.util.TypefaceUtils.getFontNames(TypefaceUtils.java:578)
W/TypefaceUtils(11263): 	at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:532)
W/TypefaceUtils(11263): 	at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:524)
W/TypefaceUtils(11263): 	at android.widget.TextView.setTypeface(TextView.java:3709)
W/TypefaceUtils(11263): 	at android.widget.TextView.setTypeface(TextView.java:2229)
W/TypefaceUtils(11263): 	at androidx.appcompat.widget.AppCompatTextView.setTypeface(AppCompatTextView.java:708)
W/TypefaceUtils(11263): 	at androidx.appcompat.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:221)
W/TypefaceUtils(11263): 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:105)
W/TypefaceUtils(11263): 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
W/TypefaceUtils(11263): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
W/TypefaceUtils(11263): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
W/TypefaceUtils(11263): 	at com.shinow.qrscan.SecondActivity.onCreate(SecondActivity.java:40)
W/TypefaceUtils(11263): 	at android.app.Activity.performCreate(Activity.java:7040)
W/TypefaceUtils(11263): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
W/TypefaceUtils(11263): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
W/TypefaceUtils(11263): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
W/TypefaceUtils(11263): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
W/TypefaceUtils(11263): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
W/TypefaceUtils(11263): 	at android.os.Handler.dispatchMessage(Handler.java:105)
W/TypefaceUtils(11263): 	at android.os.Looper.loop(Looper.java:173)
W/TypefaceUtils(11263): 	at android.app.ActivityThread.main(ActivityThread.java:6698)
W/TypefaceUtils(11263): 	at java.lang.reflect.Method.invoke(Native Method)
W/TypefaceUtils(11263): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/TypefaceUtils(11263): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
I/System.out(11263): ---------------------|||||||||||||---onAccuracyChanged---|||||||||||-------------------------

ios没试  android可以跑  但是提示上边这一堆东西

**Comment by wu9007** [comment]
@MonkeyInWind0 两件事要分开：

1. `注: QrscanPlugin.java使用或覆盖了已过时的 API` — 0.2.22 embedding v1 / `PluginRegistry.ActivityResultListener`。0.4.0 是 `FlutterPlugin` + `ActivityAware`，`ImageUtil` 已删。这条警告应该消失。
2. logcat 里大段 `miui.util.TypefaceUtils.getFontNames` NPE — 这是 **MIUI** 在 `AppCompatTextView` 上替换字体，不是 qrscan 崩溃。`SecondActivity` 仍可以打开。可以忽略。

Android 可跑、iOS 当时没试： iOS 现在有真实 `scan`（#60）。请用 git master。关闭为 completed。
