### ISSUE TITLE
Unhandled Exception:

### ISSUE THREAD

**Issue by UedaTakeyuki** [wu9007/qrcode_scanner#22]
Hello,

I'm trying this package with your example in the project.
I can succeed scan a barcord on Android device.
But on ipod touch,  I've stacked to scan with following error:

```bash:
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      scan (package:qrscan/qrscan.dart:13:47)
<asynchronous suspension>
#2      _MyAppState._scan (package:qrscan_example/main.dart:258:28)
<asynchronous suspension>
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#14     _rootRunUnary (dart:async/zone.dart:1136:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _invoke1 (dart:ui/hooks.dart:263:10)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
``` 

Do you have any suggestions about this? Thank you for your kindly help!

**Comment by wu9007** [comment]
@UedaTakeyuki Android worked; iPod touch threw from `MethodChannel.invokeMethod` at `qrscan.dart:13` (`scan`). That is the old iOS stub: no `scan` handler, so the Future never even reached a camera.

0.4.0 implements `scan` on iOS (`SwiftQrscanPlugin`, channel `qr_scan`, AVFoundation + Vision). Add `NSCameraUsageDescription` to `Info.plist`. iPod touch with a rear camera should get a full-screen scanner; cancel/Close returns `null`.

Please try git `master`. If an iPod still throws, reopen with the *new* stack (MissingPluginException vs permission vs Vision). Closing the original iOS-stub crash as completed.

**Comment by wu9007** [comment]
@UedaTakeyuki Android worked; iPod touch died inside `MethodChannel.invokeMethod` on `qrscan.dart:13` — that is MissingPlugin, not a camera failure. The iOS stub did not implement `scan`.

0.4.0 implements it. iPod touch (A10 / iOS 12+) is inside the podspec floor. Rebuild from git master. Closing as completed.
