### ISSUE TITLE
关于从相册中选择二维码文件识别后报错问题

### ISSUE THREAD

**Issue by dioig** [wu9007/qrcode_scanner#30]
我这边测试发现当从相册选择一个二维码图片进行识别的时候直接报错，
I/art     (14122): Starting a blocking GC Alloc
I/art     (14122): Starting a blocking GC Alloc
I/art     (14122): Starting a blocking GC Alloc
I/art     (14122): Clamp target GC heap from 141MB to 128MB
I/art     (14122): Alloc partial concurrent mark sweep GC freed 26(928B) AllocSpace objects, 1(20KB) LOS objects, 2% free, 125MB/128MB, paused 237us total 11.613ms
I/art     (14122): Starting a blocking GC Alloc
I/art     (14122): Clamp target GC heap from 141MB to 128MB
I/art     (14122): Alloc concurrent mark sweep GC freed 9(216B) AllocSpace objects, 0(0B) LOS objects, 2% free, 125MB/128MB, paused 286us total 24.512ms
I/art     (14122): Forcing collection of SoftReferences for 15MB allocation
I/art     (14122): Starting a blocking GC Alloc
I/art     (14122): Clamp target GC heap from 141MB to 128MB
I/art     (14122): Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 2% free, 125MB/128MB, paused 222us total 23.835ms
W/art     (14122): Throwing OutOfMemoryError "Failed to allocate a 15925260 byte allocation with 2932616 free bytes and 2MB until OOM"
I/art     (14122): WaitForGcToComplete blocked for 65.221ms for cause Background
I/art     (14122): Starting a blocking GC Alloc
I/art     (14122): Starting a blocking GC Alloc
I/art     (14122): Starting a blocking GC Alloc
I/art     (14122): Clamp target GC heap from 141MB to 128MB
I/art     (14122): Alloc partial concurrent mark sweep GC freed 4(96B) AllocSpace objects, 0(0B) LOS objects, 2% free, 125MB/128MB, paused 229us total 11.574ms
I/art     (14122): Starting a blocking GC Alloc
I/art     (14122): Clamp target GC heap from 141MB to 128MB
I/art     (14122): Alloc concurrent mark sweep GC freed 2(48B) AllocSpace objects, 0(0B) LOS objects, 2% free, 125MB/128MB, paused 227us total 23.730ms
I/art     (14122): Forcing collection of SoftReferences for 15MB allocation
I/art     (14122): Starting a blocking GC Alloc
I/art     (14122): Clamp target GC heap from 141MB to 128MB
I/art     (14122): Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 2% free, 125MB/128MB, paused 233us total 24.839ms
I/art     (14122): Starting a blocking GC HomogeneousSpaceCompact
I/art     (14122): Clamp target GC heap from 141MB to 128MB
I/art     (14122): HomogeneousSpaceCompact marksweep + semispace GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 2% free, 125MB/128MB, paused 21.214ms total 21.214ms
W/art     (14122): Throwing OutOfMemoryError "Failed to allocate a 15925260 byte allocation with 2932616 free bytes and 2MB until OOM"
D/AndroidRuntime(14122): Shutting down VM
E/AndroidRuntime(14122): FATAL EXCEPTION: main
E/AndroidRuntime(14122): Process: com.shinow.qrscan_example, PID: 14122
E/AndroidRuntime(14122): java.lang.OutOfMemoryError: Failed to allocate a 15925260 byte allocation with 2932616 free bytes and 2MB until OOM
E/AndroidRuntime(14122): 	at com.uuzuche.lib_zxing.camera.BitmapLuminanceSource.<init>(BitmapLuminanceSource.java:20)
E/AndroidRuntime(14122): 	at com.uuzuche.lib_zxing.activity.CodeUtils.analyzeBitmap(CodeUtils.java:86)
E/AndroidRuntime(14122): 	at com.uuzuche.lib_zxing.activity.CodeUtils.analyzeBitmap(CodeUtils.java:62)
E/AndroidRuntime(14122): 	at com.shinow.qrscan.QrscanPlugin.onActivityResult(QrscanPlugin.java:108)
E/AndroidRuntime(14122): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime(14122): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
E/AndroidRuntime(14122): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(14122): 	at android.app.Activity.dispatchActivityResult(Activity.java:7100)
E/AndroidRuntime(14122): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4182)
E/AndroidRuntime(14122): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4229)
E/AndroidRuntime(14122): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime(14122): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
E/AndroidRuntime(14122): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(14122): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(14122): 	at android.app.ActivityThread.main(ActivityThread.java:6256)
E/AndroidRuntime(14122): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14122): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(14122): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
I/Process (14122): Sending signal. PID: 14122 SIG: 9
Lost connection to device.

我这边测试发现很可能是因为图片文件编码问题，
因为图片经过 flutter_image_compress类压缩处理后就能识别了。
能否在从相册选择文件后，对他先进行压缩或者编码处理后在进行识别呢

**Comment by wu9007** [comment]
@dioig the crash is exact: `OutOfMemoryError` allocating ~15MB inside `com.uuzuche.lib_zxing...BitmapLuminanceSource` after picking a large album photo. You already found that `flutter_image_compress` made it work.

0.4.0 dropped `lib_zxing`. `QrDecoder.decodeFile` / `decodeBytes` / `decodeUri` now `inSampleSize` down to max 1280×1280 *before* ZXing, and recycle the bitmap. That is the compress-before-decode path you asked for, inside the plugin.

Related: #44, #67, #116. Closing this OOM as completed. Reopen if a huge album photo still OOMs on git `master`.
