### ISSUE TITLE
这个不支持iOS吧？

### ISSUE THREAD

**Issue by zhuzhengjing** [wu9007/qrcode_scanner#31]
用真机测试，报没有插件，说明上不是写了支持iOS的吗？

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method scan on channel qr_scan)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      scan (package:qrscan/qrscan.dart:13:47)
<asynchronous suspension>
#2      _HomePageState.testScanner (package:flutter_etracking/pages/home.dart:64:37)
<asynchronous suspension>
#3      _HomePageState.build.<anonymous closure> (package:flutter_etracking/pages/home.dart:52:15)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#17     _rootRunUnary (dart:async/zone.dart:1136:13)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#20     _invoke1 (dart:ui/hooks.dart:263:10)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```

**Comment by bean5** [comment]
See https://github.com/leyan95/qrcode_scanner/pull/38

**Comment by wu9007** [comment]
现在支持 iOS。`master` 上的 0.4.0 用 AVFoundation + Vision 真正扫码（相机 / 相册 / 路径 / 字节）。

`Info.plist` 要写 `NSCameraUsageDescription` 和 `NSPhotoLibraryUsageDescription`，最低 iOS 12。

pub.dev 还停在 0.3.3，先用 git：

```yaml
dependencies:
  qrscan:
    git:
      url: https://github.com/wu9007/qrcode_scanner.git
      ref: master
```

Closing as completed.

**Comment by wu9007** [comment]
@zhuzhengjing 真机 `MissingPluginException(No implementation found for method scan on channel qr_scan)` 说明 Dart 频道名没错（就是 `qr_scan`），错的是旧 iOS stub 注册的是 `qrscan`，见 #60 @Dansp 的拆解。

**不要**把 Dart 改成 `qrscan`（那会搞坏 Android）。0.4.0 `SwiftQrscanPlugin` 已经注册 `qr_scan`，`scan` / `scan_photo` / `scan_path` / `scan_bytes` / `generate_barcode` 都有实现。主工程 `Info.plist` 仍需 `NSCameraUsageDescription`。

```yaml
dependencies:
  qrscan:
    git:
      url: https://github.com/wu9007/qrcode_scanner.git
      ref: master
```

`flutter clean` 后重编 iOS。pub.dev 还是 0.3.3。关闭为 completed。
