### ISSUE TITLE
Fetal Error

### ISSUE THREAD

**Issue by halahmadi** [wu9007/qrcode_scanner#64]
Every once in a while. I get the following error

`Fatal Exception: java.lang.RuntimeException: Camera is being used after Camera.release() was called
       at android.hardware.Camera._stopPreview(Camera.java)
       at android.hardware.Camera.stopPreview(Camera.java:884)
       at com.uuzuche.lib_zxing.activity.CaptureFragment.surfaceDestroyed(CaptureFragment.java:186)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:688)
       at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:285)
       at android.view.View.dispatchWindowVisibilityChanged(View.java:10511)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1779)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1472)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7003)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:912)
       at android.view.Choreographer.doCallbacks(Choreographer.java:714)
       at android.view.Choreographer.doFrame(Choreographer.java:646)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:898)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6337)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)`

**Comment by wu9007** [comment]
@halahmadi the fatal is exact: `Camera is being used after Camera.release()` inside `com.uuzuche.lib_zxing.activity.CaptureFragment.surfaceDestroyed`. That is the old `android.hardware.Camera` + `SurfaceView` stack, racing `stopPreview` when the window hides.

0.4.0 deleted `CaptureFragment` / `lib_zxing`. Preview is CameraX `PreviewView` bound to the Activity lifecycle (`ProcessCameraProvider.bindToLifecycle`). There is no `Camera.release()` path left.

Install git master. Closing as completed. If you still see a CameraX bind crash, attach the new stack — it will not mention `CaptureFragment`.
