### ISSUE TITLE
Not Working while select QR image from storage

### ISSUE THREAD

**Issue by MR0100-zz** [wu9007/qrcode_scanner#67]
when I was try to scan QR from the storage then it return some error that I can't find even on google.

**Comment by vjgoutham** [comment]
I am also facing the same issue

**Comment by vjgoutham** [comment]
E/flutter ( 6376): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FormatException: Invalid envelope
E/flutter ( 6376): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:599:7)
E/flutter ( 6376): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 6376): <asynchronous suspension>
E/flutter ( 6376): #2      scan (package:qrscan/qrscan.dart:13:32)
E/flutter ( 6376): <asynchronous suspension>
E/flutter ( 6376): #3      _MyAppState.build.<anonymous closure>.<anonymous closure> (package:fluttertestingspeech1/main.dart:825:53)
E/flutter ( 6376): <asynchronous suspension>

**Comment by igufei** [comment]
permission_handler: ^8.1.1
获取一下存储权限
await Permission.storage.request();

**Comment by ardipermana59** [comment]
I am also facing the same issue, and solved with change skdversion in android/app/build.gradle 
`defaultConfig {
    ....
        targetSdkVersion 30 // to 28
   ....
    }`

**Comment by wu9007** [comment]
@MR0100-zz album / storage decode is the same family as #30 (OOM in `BitmapLuminanceSource`) and #44 / #116 (NotFound on huge photos). Old `lib_zxing` loaded the full bitmap.

0.4.0: `scanPhoto` / `scanPath` / `scanBytes` downsample to 1280×1280, recycle the bitmap, invert on NotFound. No `uuzuche` types on the stack.

Please retry on git master. If it still fails, the photo itself matters — attach it. Closing this as completed on the plugin side.
