### ISSUE TITLE
Fatal exception when torch is clicked on a device which has no flashlight.

### ISSUE THREAD

**Issue by ChinHairSaintClair** [wu9007/qrcode_scanner#70]
`java.lang.RuntimeException: setParameters failed
E/AndroidRuntime(24312): 	at android.hardware.Camera.native_setParameters(Native Method)
E/AndroidRuntime(24312): 	at android.hardware.Camera.setParameters(Camera.java:2162)
E/AndroidRuntime(24312): 	at com.uuzuche.lib_zxing.activity.CodeUtils.isLightEnable(CodeUtils.java:211)
E/AndroidRuntime(24312): 	at com.shinow.qrscan.SecondActivity$1.onClick(SecondActivity.java:75)
E/AndroidRuntime(24312): 	at android.view.View.performClick(View.java:7346)
E/AndroidRuntime(24312): 	at android.view.View.performClickInternal(View.java:7312)
E/AndroidRuntime(24312): 	at android.view.View.access$3200(View.java:846)
E/AndroidRuntime(24312): 	at android.view.View$PerformClick.run(View.java:27801)
E/AndroidRuntime(24312): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(24312): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24312): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(24312): 	at android.app.ActivityThread.main(ActivityThread.java:7156)
E/AndroidRuntime(24312): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24312): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(24312): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
I/Process (24312): Sending signal. PID: 24312 SIG: 9
Lost connection to device.
`

**Comment by Cybernetics354** [comment]
this issue occured on my app too, is there any solution about this?

**Comment by tfbsza** [comment]
same problem here. it would be helpful if there was an option to disable/hide the flashlight.

**Comment by Cybernetics354** [comment]
im ended up fork and change the java codes by myself, and i add some try catch on turn on/off callback so i can handle if there's exception occured.

file on `SecondActivity.java`

```java
try {
  CodeUtils.isLightEnable(true);
  isLightOpen = true;
} catch (Exception e) {
  // Exception handler here
  Toast.makeText(getApplicationContext(), "Tidak bisa menyalakan senter", Toast.LENGTH_SHORT).show();
}
```

**Comment by tfbsza** [comment]
that is a good interim solution, thanks for posting it. this should be part of the baseline functionality of the package. maintaining custom forks can be problematic in terms of future updates and fixes.

**Comment by Cybernetics354** [comment]
yeah i think so, in case you want to fix this issue ASAP, you can use that alternative. i've made a pull request for this. but i can't wait for the maintainer accept this so right now im using custom fork until it accepted or fixed by them.

and also sorry for my bad english :")

**Comment by wu9007** [comment]
Fixed on `master` (qrscan 0.4.0).

Torch goes through CameraX `enableTorch`. Devices without a flash toast "Can't use light" instead of crashing.

Closing as completed.

**Comment by wu9007** [comment]
@ChinHairSaintClair the crash is `Camera.native_setParameters` from `com.uuzuche.lib_zxing.activity.CodeUtils.isLightEnable` on a device without a flashlight — old Camera1 API, no try/catch.

0.4.0 torch is CameraX `camera.getCameraControl().enableTorch(...)` inside try/catch. No flashlight / bind failure → toast `Can't use light`, no process death. `lib_zxing` / `CodeUtils` are gone.

Install git master. Closing as completed.
