### ISSUE TITLE
QR CODE SCAN (qrscan)  DOES NOT WORK

### ISSUE THREAD

**Issue by S7071** [wu9007/qrcode_scanner#90]
Trying to scan a QR code but nothing happens. Worked fine for the last 2 months then today it unexpectedly stopped working after i uninstalled my app from my device. Tried flutter clean and even upgraded the package but problem still persists. 

Flutter doctor results
`[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.746], locale en-KE)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

• No issues found!`

Debug Log
`Launching lib\main.dart on SM A530W in debug mode...
 lib\main.dart
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:50707/yyVA9CddjRg=/ws
D/ViewRootImpl@148d258[MainActivity]( 9662): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={true 543581724672} changed=false
W/ConnectionTracker( 9662): Exception thrown while unbinding
W/ConnectionTracker( 9662): java.lang.IllegalArgumentException: Service not registered: ls@557d382
W/ConnectionTracker( 9662): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1680)
W/ConnectionTracker( 9662): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
W/ConnectionTracker( 9662): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
W/ConnectionTracker( 9662): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):1)
W/ConnectionTracker( 9662): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):2)
W/ConnectionTracker( 9662): 	at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):9)
W/ConnectionTracker( 9662): 	at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):3)
W/ConnectionTracker( 9662): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):3)
W/ConnectionTracker( 9662): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
W/ConnectionTracker( 9662): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker( 9662): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):5)
I/flutter ( 9662): SVG Warning: Discarding:
I/flutter ( 9662):
I/flutter ( 9662):   <polyline id="XMLID_365_" style="display:none;opacity:0.6;" points="161.941,64.197 161.941,202.053 184.473,208.56 &#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;184.546,64.197 161.941,64.197 &#x9;&#x9;&#x9;&#x9;&#x9;&#x9;"/>
I/flutter ( 9662):
I/flutter ( 9662): and any children it has since it is not visible.
I/flutter ( 9662): If that element is meant to be visible, the `display` or `visibility` attributes should be removed.
I/flutter ( 9662): If that element is not meant to be visible, it would be better to remove it from the SVG file.
I/flutter ( 9662): SVG Warning: Discarding:
I/flutter ( 9662):
I/flutter ( 9662):   <polygon id="XMLID_234_" style="display:none;opacity:0.3;" points="125.54,57.937 125.54,62.699 125.54,64.197 &#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;125.54,208.56 132.934,208.56 132.934,64.197 176.336,64.197 176.336,208.56 184.473,208.56 184.473,64.197 184.473,62.699 &#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;184.473,57.937 &#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;"/>
I/flutter ( 9662):
I/flutter ( 9662): and any children it has since it is not visible.
I/flutter ( 9662): If that element is meant to be visible, the `display` or `visibility` attributes should be removed.
I/flutter ( 9662): If that element is not meant to be visible, it would be better to remove it from the SVG file.
I/flutter ( 9662): SVG Warning: Discarding:
I/flutter ( 9662):
I/flutter ( 9662):   <rect id="XMLID_735_" x="147.928" y="49.149" style="display:none;opacity:0.3;" width="12.145" height="2.712"/>
I/flutter ( 9662):
I/flutter ( 9662): and any children it has since it is not visible.
I/flutter ( 9662): If that element is meant to be visible, the `display` or `visibility` attributes should be removed.
I/flutter ( 9662): If that element is not meant to be visible, it would be better to remove it from the SVG file.
D/ViewRootImpl@148d258[MainActivity]( 9662): ViewPostIme pointer 0
D/ViewRootImpl@148d258[MainActivity]( 9662): ViewPostIme pointer 1
W/ActivityThread( 9662): handleWindowVisibility: no activity for token android.os.BinderProxy@433a5ce
W/isdesign.studi( 9662): Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
W/isdesign.studi( 9662): Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
W/isdesign.studi( 9662): Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
W/isdesign.studi( 9662): Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
W/isdesign.studi( 9662): Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
I/DecorView( 9662): createDecorCaptionView >> DecorView@d6a8fdf[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
W/isdesign.studi( 9662): Accessing hidden method Landroid/view/View;->getAccessibilityDelegate()Landroid/view/View$AccessibilityDelegate; (light greylist, linking)
W/isdesign.studi( 9662): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/isdesign.studi( 9662): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
W/isdesign.studi( 9662): Accessing hidden method Landroid/widget/TextView;->getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)
D/SensorManager( 9662): registerListener :: 5, TMD3725 Light, 200000, 0,
I/MediaPlayer( 9662): Need to enable context aware info
V/MediaPlayer-JNI( 9662): native_setup
V/MediaPlayerNative( 9662): constructor
V/MediaPlayerNative( 9662): setListener
W/MediaPlayer( 9662): Use of stream types is deprecated for operations other than volume control
W/MediaPlayer( 9662): See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
V/MediaPlayer-JNI( 9662): setVolume: left 1.000000  right 1.000000
V/MediaPlayerNative( 9662): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI( 9662): setAuxEffectSendLevel: level 0.000000
V/MediaPlayerNative( 9662): MediaPlayer::setAuxEffectSendLevel(0.000000)
V/MediaPlayer-JNI( 9662): setAudioStreamType: 3
V/MediaPlayerNative( 9662): MediaPlayer::setAudioStreamType
V/MediaPlayer-JNI( 9662): setDataSourceFD: fd 102
V/MediaPlayerNative( 9662): setDataSource(102, 2102196, 6401)
V/MediaPlayer-JNI( 9662): setVolume: left 0.100000  right 0.100000
V/MediaPlayerNative( 9662): MediaPlayer::setVolume(0.100000, 0.100000)
V/MediaPlayerNative( 9662): setVideoSurfaceTexture
V/MediaPlayerNative( 9662): prepare
V/MediaPlayerNative( 9662): message received msg=200, ext1=10973, ext2=0
W/MediaPlayerNative( 9662): info/warning (10973, 0)
V/MediaPlayerNative( 9662): callback application
V/MediaPlayerNative( 9662): back from callback
V/MediaPlayerNative( 9662): message received msg=1, ext1=0, ext2=0
V/MediaPlayerNative( 9662): MediaPlayer::notify() prepared
V/MediaPlayerNative( 9662): signal application thread
V/MediaPlayerNative( 9662): callback application
V/MediaPlayerNative( 9662): prepare complete - status=0
V/MediaPlayerNative( 9662): back from callback
V/MediaPlayerNative( 9662): invoke 68
D/InputTransport( 9662): Input channel constructed: fd=108
D/ViewRootImpl@b2fea[SecondActivity]( 9662): setView = DecorView@d6a8fdf[SecondActivity] TM=true MM=false
D/ViewRootImpl@148d258[MainActivity]( 9662): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 9662): prepareNavigationBarInfo() DecorView@47c83be[MainActivity]
D/InputMethodManager( 9662): getNavigationBarColor() -15906911
V/MediaPlayerNative( 9662): invoke 68
D/SurfaceView( 9662): onWindowVisibilityChanged(0) true android.view.SurfaceView{658e2db V.E...... ......I. 0,0-0,0 #7f0800b6 app:id/preview_view} of ViewRootImpl@b2fea[SecondActivity]
D/ViewRootImpl@b2fea[SecondActivity]( 9662): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x7 surface={true 542879240192} changed=true
D/mali_winsys( 9662): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer( 9662): eglCreateWindowSurface = 0x7e66b75a80, 0x7e661fd010
D/SurfaceView( 9662): show() Surface(name=SurfaceView - com.thisdesign.studio/com.shinow.qrscan.SecondActivity@658e2db@0[9662])/@0x9598178 android.view.SurfaceView{658e2db V.E...... ......ID 0,0-1080,2103 #7f0800b6 app:id/preview_view}
D/SurfaceView( 9662): surfaceCreated 1 #8 android.view.SurfaceView{658e2db V.E...... ......ID 0,0-1080,2103 #7f0800b6 app:id/preview_view}
E/Camera_APM : ( 9662): [APM]APM's Thread is started
E/Camera_APM : ( 9662): [APM] This app is forground app
D/CameraConfigurationManager( 9662): Default preview format: 17/yuv420sp
D/CameraConfigurationManager( 9662): Screen resolution: Point(1080, 2175)
I/#########( 9662): screenX:2175   screenY:1080
D/CameraConfigurationManager( 9662): preview-size-values parameter: 1920x1080,1440x1080,1088x1088,1280x720,1056x704,1024x768,960x720,720x720,720x480,640x480,352x288,320x240,256x144,176x144
D/CameraConfigurationManager( 9662): Camera resolution: Point(1080, 2175)
D/CameraConfigurationManager( 9662): Setting preview size: Point(1920, 1080)
W/isdesign.studi( 9662): Accessing hidden method Landroid/os/ServiceManager;->getService(Ljava/lang/String;)Landroid/os/IBinder; (light greylist, reflection)
V/FlashlightManager( 9662): This device does supports control of a flashlight
D/SurfaceView( 9662): surfaceChanged (1080,2103) 1 #8 android.view.SurfaceView{658e2db V.E...... ......ID 0,0-1080,2103 #7f0800b6 app:id/preview_view}
I/System.out( 9662): ---------------------|||||||||||||---onAccuracyChanged---|||||||||||-------------------------
D/ViewRootImpl@b2fea[SecondActivity]( 9662): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x3 surface={true 542879240192} changed=false
D/ViewRootImpl@b2fea[SecondActivity]( 9662): MSG_RESIZED: frame=[0,0][1080,2220] ci=[0,72][0,45] vi=[0,72][0,45] or=1
D/ViewRootImpl@b2fea[SecondActivity]( 9662): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager( 9662): prepareNavigationBarInfo() DecorView@d6a8fdf[SecondActivity]
D/InputMethodManager( 9662): getNavigationBarColor() -855310
D/InputMethodManager( 9662): prepareNavigationBarInfo() DecorView@d6a8fdf[SecondActivity]
D/InputMethodManager( 9662): getNavigationBarColor() -855310
V/InputMethodManager( 9662): Starting input: tba=com.thisdesign.studio ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 9662): startInputInner - Id : 0
I/InputMethodManager( 9662): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 9662): Input channel constructed: fd=117
D/InputTransport( 9662): Input channel destroyed: fd=103
I/isdesign.studi( 9662): Background concurrent copying GC freed 2774(252KB) AllocSpace objects, 3(172KB) LOS objects, 50% free, 9MB/19MB, paused 1.859ms total 118.457ms
D/SurfaceView( 9662): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{4f34c96 V.E...... ........ 0,0-1080,2175} of ViewRootImpl@148d258[MainActivity]
D/SurfaceView( 9662): show() Surface(name=SurfaceView - com.thisdesign.studio/com.example.inventory_app.MainActivity@4f34c96@0[9662])/@0x88575ed io.flutter.embedding.android.FlutterSurfaceView{4f34c96 V.E...... ........ 0,0-1080,2175}
D/SurfaceView( 9662): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{4f34c96 V.E...... ........ 0,0-1080,2175}
W/libEGL  ( 9662): EGLNativeWindowType 0x7e900da010 disconnect failed
D/SurfaceView( 9662): destroy() Surface(name=SurfaceView - com.thisdesign.studio/com.example.inventory_app.MainActivity@4f34c96@0[9662])/@0x88575ed io.flutter.embedding.android.FlutterSurfaceView{4f34c96 V.E...... ........ 0,0-1080,2175}
W/libEGL  ( 9662): EGLNativeWindowType 0x7e8ffee010 disconnect failed
D/OpenGLRenderer( 9662): eglDestroySurface = 0x7ea28a7f80, 0x7e8ffee000
D/ViewRootImpl@148d258[MainActivity]( 9662): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x5 surface={false 0} changed=true
D/ViewRootImpl@148d258[MainActivity]( 9662): stopped(true) old=false
D/SurfaceView( 9662): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{4f34c96 V.E...... ........ 0,0-1080,2175} of ViewRootImpl@148d258[MainActivity]
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 1
W/ConnectionTracker( 9662): Exception thrown while unbinding
W/ConnectionTracker( 9662): java.lang.IllegalArgumentException: Service not registered: ls@557d382
W/ConnectionTracker( 9662): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1680)
W/ConnectionTracker( 9662): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
W/ConnectionTracker( 9662): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
W/ConnectionTracker( 9662): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):1)
W/ConnectionTracker( 9662): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):2)
W/ConnectionTracker( 9662): 	at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):9)
W/ConnectionTracker( 9662): 	at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):3)
W/ConnectionTracker( 9662): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):3)
W/ConnectionTracker( 9662): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
W/ConnectionTracker( 9662): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker( 9662): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):5)
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 1
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme key 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme key 1
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme key 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme key 1
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme key 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme key 1
I/isdesign.studi( 9662): Background concurrent copying GC freed 1031(128KB) AllocSpace objects, 12(18MB) LOS objects, 49% free, 9MB/19MB, paused 322us total 104.407ms
I/isdesign.studi( 9662): Background concurrent copying GC freed 1432(175KB) AllocSpace objects, 16(25MB) LOS objects, 50% free, 15MB/31MB, paused 197us total 104.761ms
I/isdesign.studi( 9662): Background concurrent copying GC freed 354(128KB) AllocSpace objects, 16(25MB) LOS objects, 50% free, 15MB/31MB, paused 154us total 114.180ms
I/isdesign.studi( 9662): Background concurrent copying GC freed 357(144KB) AllocSpace objects, 16(25MB) LOS objects, 50% free, 9MB/19MB, paused 192us total 112.755ms
I/isdesign.studi( 9662): Waiting for a blocking GC ProfileSaver
I/isdesign.studi( 9662): WaitForGcToComplete blocked ProfileSaver on HeapTrim for 8.428ms
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 1
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 1
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 1
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 1
I/isdesign.studi( 9662): Background concurrent copying GC freed 460(127KB) AllocSpace objects, 16(25MB) LOS objects, 49% free, 9MB/19MB, paused 250us total 101.447ms
I/isdesign.studi( 9662): Background concurrent copying GC freed 871(159KB) AllocSpace objects, 16(25MB) LOS objects, 49% free, 15MB/31MB, paused 135us total 119.293ms
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 1
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 1
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 0
D/ViewRootImpl@b2fea[SecondActivity]( 9662): ViewPostIme pointer 1
D/SensorManager( 9662): unregisterListener ::
D/ViewRootImpl@148d258[MainActivity]( 9662): stopped(false) old=true
D/SurfaceView( 9662): windowStopped(false) false io.flutter.embedding.android.FlutterSurfaceView{4f34c96 V.E...... ........ 0,0-1080,2175} of ViewRootImpl@148d258[MainActivity]
D/ViewRootImpl@148d258[MainActivity]( 9662): stopped(false) old=false
D/ViewRootImpl@b2fea[SecondActivity]( 9662): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 9662): prepareNavigationBarInfo() DecorView@d6a8fdf[SecondActivity]
D/InputMethodManager( 9662): getNavigationBarColor() -855310
D/SurfaceView( 9662): onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{4f34c96 V.E...... ........ 0,0-1080,2175} of ViewRootImpl@148d258[MainActivity]
D/ViewRootImpl@148d258[MainActivity]( 9662): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x7 surface={true 542878195712} changed=true
D/mali_winsys( 9662): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer( 9662): eglCreateWindowSurface = 0x7ea0954d80, 0x7e660fe010
D/SurfaceView( 9662): show() Surface(name=SurfaceView - com.thisdesign.studio/com.example.inventory_app.MainActivity@4f34c96@1[9662])/@0x4fb1cec io.flutter.embedding.android.FlutterSurfaceView{4f34c96 V.E...... ........ 0,0-1080,2175}
D/SurfaceView( 9662): surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{4f34c96 V.E...... ........ 0,0-1080,2175}
D/mali_winsys( 9662): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView( 9662): surfaceChanged (1080,2175) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{4f34c96 V.E...... ........ 0,0-1080,2175}
D/ViewRootImpl@148d258[MainActivity]( 9662): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager( 9662): prepareNavigationBarInfo() DecorView@47c83be[MainActivity]
D/InputMethodManager( 9662): getNavigationBarColor() -15906911
D/InputMethodManager( 9662): prepareNavigationBarInfo() DecorView@47c83be[MainActivity]
D/InputMethodManager( 9662): getNavigationBarColor() -15906911
V/InputMethodManager( 9662): Starting input: tba=com.thisdesign.studio ic=null mNaviBarColor -15906911 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 9662): startInputInner - Id : 0
I/InputMethodManager( 9662): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 9662): Input channel constructed: fd=104
D/InputTransport( 9662): Input channel destroyed: fd=117
D/SurfaceView( 9662): onWindowVisibilityChanged(8) false android.view.SurfaceView{658e2db V.E...... ........ 0,0-1080,2103 #7f0800b6 app:id/preview_view} of ViewRootImpl@b2fea[SecondActivity]
D/SurfaceView( 9662): show() Surface(name=SurfaceView - com.thisdesign.studio/com.shinow.qrscan.SecondActivity@658e2db@0[9662])/@0x9598178 android.view.SurfaceView{658e2db V.E...... ........ 0,0-1080,2103 #7f0800b6 app:id/preview_view}
D/SurfaceView( 9662): surfaceDestroyed callback.size 1 #2 android.view.SurfaceView{658e2db V.E...... ........ 0,0-1080,2103 #7f0800b6 app:id/preview_view}
D/SurfaceView( 9662): destroy() Surface(name=SurfaceView - com.thisdesign.studio/com.shinow.qrscan.SecondActivity@658e2db@0[9662])/@0x9598178 android.view.SurfaceView{658e2db V.E...... ........ 0,0-1080,2103 #7f0800b6 app:id/preview_view}
W/libEGL  ( 9662): EGLNativeWindowType 0x7e661fd010 disconnect failed
D/OpenGLRenderer( 9662): eglDestroySurface = 0x7e66b75a80, 0x7e661fd000
D/ViewRootImpl@b2fea[SecondActivity]( 9662): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x5 surface={false 0} changed=true
D/ViewRootImpl@b2fea[SecondActivity]( 9662): stopped(true) old=false
D/SurfaceView( 9662): windowStopped(true) false android.view.SurfaceView{658e2db V.E...... ........ 0,0-1080,2103 #7f0800b6 app:id/preview_view} of ViewRootImpl@b2fea[SecondActivity]
D/ViewRootImpl@b2fea[SecondActivity]( 9662): dispatchDetachedFromWindow
D/InputTransport( 9662): Input channel destroyed: fd=108
W/ConnectionTracker( 9662): Exception thrown while unbinding
W/ConnectionTracker( 9662): java.lang.IllegalArgumentException: Service not registered: ls@557d382
W/ConnectionTracker( 9662): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1680)
W/ConnectionTracker( 9662): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
W/ConnectionTracker( 9662): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
W/ConnectionTracker( 9662): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):1)
W/ConnectionTracker( 9662): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):2)
W/ConnectionTracker( 9662): 	at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):9)
W/ConnectionTracker( 9662): 	at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):3)
W/ConnectionTracker( 9662): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):3)
W/ConnectionTracker( 9662): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
W/ConnectionTracker( 9662): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker( 9662): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204714067@20.47.14 (100408-0):5)
`
Help...

**Comment by wu9007** [comment]
@S7071 SM A530W log is the **old** stack, not 0.4.0:

- `CameraConfigurationManager` / `preview-size-values` / `FlashlightManager` → uuzuche Camera1
- `I/MediaPlayer` + `setDataSourceFD` → beep wav
- `SurfaceView ... app:id/preview_view` of `SecondActivity`

`scan()` *did* open `SecondActivity` (so this is not MissingPlugin). It then never returned a code. Possible: preview size 1920×1080 forced onto a portrait 1080×2175 screen (`screenX:2175 screenY:1080` in the log), or decode never hitting.

0.4.0 replaced all of that with CameraX + no MediaPlayer. I will **not** close this from an old Camera1 log. Please retry on git `master` and paste a new logcat. If it still fails on A530W, this stays open.

**Comment by wu9007** [comment]
@S7071 this issue stays **open**. I will not close it from an old log.

Your log is SM-A530W, Flutter 1.22.5, app `com.thisdesign.studio`, after an uninstall. `scan()` **did** open `SecondActivity` (not MissingPlugin). Then nothing came back. Concrete lines from **that** log:

- `CameraConfigurationManager` / `preview-size-values` / `FlashlightManager` → old uuzuche Camera1
- `I/######### screenX:2175 screenY:1080` on a portrait 1080×2175 window → preview size axes swapped
- `I/MediaPlayer` + `setDataSourceFD` → beep wav on every open
- `SurfaceView … app:id/preview_view` of `SecondActivity`
- repeated LOS GC of 18–25 MB while you tapped and nothing decoded
- “worked two months, died after uninstall” → CAMERA permission is gone after reinstall (0.2.20 removed install-time CAMERA)

None of that code exists on git `master`. Camera1 + MediaPlayer are gone. CameraX binds with PreviewView `COMPATIBLE` (TextureView, better on older Samsung). Live decode downsamples; QR is tried with `TRY_HARDER` before UPC-E. Permission is requested at `scan()`. Bind failure finishes the Activity with `CAMERA_START_FAILED` / `CAMERA_IN_USE` instead of sitting black.

That is a stack replacement, **not** a retest on A530W. I do not have that device.

Please install git `master` and capture **only** `Qrscan` (plus crash):

```
adb logcat -s Qrscan:* AndroidRuntime:E
```

```yaml
qrscan:
  git:
    url: https://github.com/wu9007/qrcode_scanner.git
    ref: master
```

What I need from you:

1. After uninstall, does the CAMERA prompt appear when you tap Scan? Grant it.
2. A healthy start logs `Qrscan: camera bound rotation=… preview=WxH`. If you still see `CameraConfigurationManager` / `MediaPlayer`, you are not on this `master`.
3. A successful decode logs `Qrscan: decoded length=N` and the example result field fills.
4. If bound but never `decoded`, say so and paste that short log. If bind fails, Dart should show `CAMERA_START_FAILED` / `CAMERA_IN_USE` / `PERMISSION_NOT_GRANTED` in the example result field — paste that string.

Until that A530W log exists, this stays open.
